LibraryCoreProject/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;

namespace LibraryCoreProject.Models
{
    public class User: IdentityUser
    {
        public ICollection<Booking> Bookings { get; set; }
        public ICollection<Subscription> Subscriptions { get; set; }

        public User()
        {
            Bookings = new List<Booking>();
            Subscriptions = new List<Subscription>();
        }
    }
}

LibraryCoreProject/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LibraryCoreProject.Models;
using LibraryCoreProject.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace LibraryCoreProject.Controllers
{
    public class RolesController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public RolesController(UserManager<User> userManager, RoleManager<IdentityRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            return View(_roleManager.Roles.ToList());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            if (!string.IsNullOrEmpty(name))
            {
                IdentityResult result = await _roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, error.Description);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            if (role != null)
            {
                await _roleManager.DeleteAsync(role);
            }
            return RedirectToAction("Index");
        }

        public IActionResult UserList()
        {
            return View(_userManager.Users.ToList());
        }

        public async Task<IActionResult> Edit(string userId)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                ChangeRoleViewModel model = new ChangeRoleViewModel
                {
                    Id = user.Id,
                    Email = user.Email,
                    UserRoles = userRoles,
                    AllRoles = allRoles
                };
                return View(model);
            }

            return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> Edit(string userId, List<string> roles)
        {
            User user = await _userManager.FindByIdAsync(userId);
            if (user != null)
            {
                var userRoles = await _userManager.GetRolesAsync(user);
                var allRoles = _roleManager.Roles.ToList();
                var addedRoles = roles.Except(userRoles);
                var removedRoles = userRoles.Except(roles);

                await _userManager.AddToRolesAsync(user, addedRoles);
                await _userManager.RemoveFromRolesAsync(user, removedRoles);

                return RedirectToAction("Index","Users");
            }

            return NotFound();
        }
    }
}

LibraryCoreProject/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LibraryCoreProject.Models;
using LibraryCoreProject.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace LibraryCoreProject.Controllers
{
    [Authorize(Roles ="admin")]
    public class UsersController : Controller
    {
        private readonly UserManager<User> _userManager;

        public UsersController(UserManager<User> userManager)
        {
            _userManager = userManager;
        }
        
        public IActionResult Index()
        {
            return View(_userManager.Users.ToList());
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = new User { Email = model.Email, UserName = model.Email };
                var result = await _userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach(var Error in result.Errors)
                    {
                        ModelState.AddModelError("", Error.Description);
                    }
                }
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            EditUserViewModel model = new EditUserViewModel { Email = user.Email, Id = user.Id };

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    user.Email = model.Email;
                    user.UserName = model.Email;
                    var result = await _userManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach(var Error in result.Errors)
                        {
                            ModelState.AddModelError("", Error.Description);
                        }
                    }
                }
            }
            return View(model);

        }
        public async Task<IActionResult> Delete(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user != null)
            {
                await _userManager.DeleteAsync(user);
            }
            return RedirectToAction("Index");
        }


    }
}

LibraryCoreProject/Views/Users/Create.cshtml
@model LibraryCoreProject.ViewModels.CreateUserViewModel
@{
    ViewData["Title"] = "Добавление пользователя";
}

    <form asp-action="Create" asp-controller="Users">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Email" class="control-label">Email</label>
            <input type="text" asp-for="Email" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Password" class="control-label">Пароль</label>
            <input type="password" asp-for="Password" class="form-control" />
        </div>
        <div class="form-group">
            <input type="submit" value="Добавить" class="btn btn-outline-secondary" />
        </div>
    </form>

LibraryCoreProject/Views/Users/Edit.cshtml
@model LibraryCoreProject.ViewModels.EditUserViewModel
@{
    ViewData["Title"] = "Редактирование пользователя";
}

    <form asp-action="Edit" asp-controller="Users">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <input type="hidden" asp-for="Id" />
        </div>
        <div class="form-group">
            <label asp-for="Email" class="control-label">Email</label>
            <input type="text" asp-for="Email" class="form-control" />
        </div>
        <div class="form-group">
            <input type="submit" value="Сохранить" class="btn btn-outline-secondary" />
        </div>
    </form>

LibraryCoreProject/Views/Users/Index.cshtml
@model IEnumerable<LibraryCoreProject.Models.User>
@{
    ViewData["Title"] = "Index";
}

<a asp-action="Create">Добавить пользователя</a>

<table class="table">
    <tr><th>Email</th><th></th><th></th></tr>
    @foreach (var user in Model)
    {
<tr>
    <td>@user.Email</td>
    <td>
        <form asp-action="Delete" asp-route-id="@user.Id" method="post">
            <a class="btn btn-sm btn-primary" asp-action="Edit" asp-route-id="@user.Id">Изменить</a>
            <button type="submit" class="btn btn-sm btn-danger">
                Удалить
            </button>
        </form>
    </td>
    <td>
        <a class="btn btn-sm btn-primary" asp-action="Edit" asp-controller="Roles" asp-route-userid="@user.Id">Права доступа</a>
    </td>
</tr>
    }
</table>