LibraryCoreProject/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryCoreProject.Models
{
    public class Book
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int GenreId { get; set; }
        public Genre Genre { get; set; }
        public int AuthorId { get; set; }
        public Author Author { get; set; }
        public int PublisherId { get; set; }
        public Publisher Publisher { get; set; }

        // Доступна ли книга?
        public bool isAvailable { get; set; }

        public Book()
        {
            isAvailable = true;
        }
    }
}

LibraryCoreProject/ViewModels/AddBookViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LibraryCoreProject.ViewModels
{
    public class AddBookViewModel : IValidatableObject
    {
        public int BookId { get; set; }
        [Required(ErrorMessage = "Введите название книги")]
        [Display(Name = "Название")]
        public string Name { get; set; }


        public bool isNewAuthor { get; set; }
        public int AuthorId { get; set; }
        public IEnumerable<SelectListItem> Authors { get; set; }
        public string AuthorName { get; set; }


        public bool isNewGenre { get; set; }
        public int GenreId { get; set; }
        public IEnumerable<SelectListItem> Genres { get; set; }
        public string GenreName { get; set; }

        public bool isNewPublisher { get; set; }
        public int PublisherId { get; set; }
        public IEnumerable<SelectListItem> Publishers { get; set; }
        public string PublisherName { get; set; }
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            List<ValidationResult> errors = new List<ValidationResult>();

            if( isNewAuthor && string.IsNullOrEmpty(AuthorName))
            {
                errors.Add(new ValidationResult("Введите имя автора", new[] {"AuthorName" }));
            }

            if( isNewGenre && string.IsNullOrEmpty(GenreName))
            {
                errors.Add(new ValidationResult("Введите название жанра", new[] { "GenreName" }));
            }

            if (isNewPublisher && string.IsNullOrEmpty(PublisherName))
            {
                errors.Add(new ValidationResult("Введите название издателя", new[] { "PublisherName" }));
            }

            return errors;
        }
    }
}

LibraryCoreProject/ViewModels/DeleteBookViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryCoreProject.ViewModels
{
    public class DeleteBookViewModel
    {
        public int BookId { get; set; }
        [Display(Name="Название книги:")]
        public string BookName { get; set; }
        [Display(Name ="Жанр:")]
        public string GenreName { get; set; }
        [Display(Name = "Автор:")]
        public string AuthorName { get; set; }
        [Display(Name = "Издатель:")]
        public string PublisherName { get; set; }
    }
}

LibraryCoreProject/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LibraryCoreProject.Models;
using LibraryCoreProject.Repositories;
using LibraryCoreProject.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LibraryCoreProject.Controllers
{
    [Authorize(Roles="admin,librarian")]
    public class BookController: Controller
    {
        private readonly IUnitOfWork unitOfWork;
        public BookController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        
        public ActionResult BookList(int? AuthorId, int? GenreId, int? PublihserId, string SearchString = null)
        {
            List<Author> authors = unitOfWork.Authors.GetItemList().ToList();
            List<Genre> genres = unitOfWork.Genres.GetItemList().ToList();
            List<Publisher> publishers = unitOfWork.Publishers.GetItemList().ToList();
            List<Book> books = unitOfWork.Books.GetFilteredList(AuthorId, GenreId, PublihserId, SearchString).ToList();

            BooksFilterViewModel model = new BooksFilterViewModel
            {
                Authors = new SelectList(authors, "AuthorId", "AuthorName"),
                Genres = new SelectList(genres, "GenreId", "GenreName"),
                Publishers = new SelectList(publishers, "PublisherId", "PublisherName"),
                SearchString = String.Empty,
                Books=books
            };

            return View(model);
            
        }
        #region Добавление книги
        [HttpGet]
        public ActionResult AddBook()
        {
            List<Author> authors = unitOfWork.Authors.GetItemList().ToList();
            List<Genre> genres = unitOfWork.Genres.GetItemList().ToList();
            List<Publisher> publishers = unitOfWork.Publishers.GetItemList().ToList();

            AddBookViewModel model = new AddBookViewModel
            {
                Authors = new SelectList(authors, "AuthorId", "AuthorName"),
                Genres = new SelectList(genres, "GenreId", "GenreName"),
                Publishers = new SelectList(publishers, "PublisherId", "PublisherName")
            };
            return View(model);
        }
        [HttpPost]
        public ActionResult AddBook(AddBookViewModel model)
        {
            if (ModelState.IsValid)
            {
                Author author;
                Genre genre;
                Publisher publisher;

                if (model.isNewAuthor)
                {
                    author = new Author { AuthorName = model.AuthorName };
                    unitOfWork.Authors.Create(author);
                    unitOfWork.Save();
                }
                else
                {
                    author = unitOfWork.Authors.GetItem(model.AuthorId);
                }

                if (model.isNewGenre)
                {
                    genre = new Genre { GenreName = model.GenreName };
                    unitOfWork.Genres.Create(genre);
                    unitOfWork.Save();
                }
                else
                {
                    genre = unitOfWork.Genres.GetItem(model.GenreId);
                }

                if (model.isNewPublisher)
                {
                    publisher = new Publisher { PublisherName = model.PublisherName };
                    unitOfWork.Publishers.Create(publisher);
                    unitOfWork.Save();
                }
                else
                {
                    publisher = unitOfWork.Publishers.GetItem(model.PublisherId);
                }

                Book book = new Book
                {
                    Name = model.Name,
                    AuthorId = author.AuthorId,
                    PublisherId = publisher.PublisherId,
                    GenreId = genre.GenreId
                };

                unitOfWork.Books.Create(book);
                unitOfWork.Save();

                return RedirectToAction("BookList");
               
            }
            else
            {
                var authors = unitOfWork.Authors.GetItemList();
                var genres = unitOfWork.Genres.GetItemList();
                var publishers = unitOfWork.Publishers.GetItemList();


                model.Authors = new SelectList(authors, "AuthorId", "AuthorName");
                model.Genres = new SelectList(genres, "GenreId", "GenreName");
                model.Publishers = new SelectList(publishers, "PublisherId", "PublisherName");

                return View(model);
            }
        }


       
        #endregion
        #region Редактирование книги
        [HttpGet]
        public ActionResult EditBook(int id)
        {
            if (unitOfWork.Books.GetItem(id) != null)
            {
                Book book = unitOfWork.Books.GetItem(id);
                List<Author> authors = unitOfWork.Authors.GetItemList().ToList();
                List<Genre> genres = unitOfWork.Genres.GetItemList().ToList();
                List<Publisher> publishers = unitOfWork.Publishers.GetItemList().ToList();

                AddBookViewModel model = new AddBookViewModel
                {
                    BookId = book.Id,
                    Name = book.Name,
                    AuthorId = book.AuthorId,
                    GenreId = book.GenreId,
                    PublisherId = book.PublisherId,

                    Authors = new SelectList(authors, "AuthorId", "AuthorName"),
                    Genres = new SelectList(genres, "GenreId", "GenreName"),
                    Publishers = new SelectList(publishers, "PublisherId", "PublisherName")
                };
                return View(model);
            }
            else
            {
                return NotFound();
            }
        }
        [HttpPost]
        public IActionResult EditBook(AddBookViewModel model)
        {
            if (ModelState.IsValid)
            {
                Author author = new Author();
                Genre genre = new Genre();
                Publisher publisher = new Publisher();

                if (model.isNewAuthor)
                {
                    author = new Author { AuthorName = model.AuthorName };
                    unitOfWork.Authors.Create(author);
                    unitOfWork.Save();
                }
                else
                {
                    author = unitOfWork.Authors.GetItem(model.AuthorId);
                }

                if (model.isNewGenre)
                {
                    genre = new Genre { GenreName = model.GenreName };
                    unitOfWork.Genres.Create(genre);
                    unitOfWork.Save();
                }
                else
                {
                    genre = unitOfWork.Genres.GetItem(model.GenreId);
                }

                if (model.isNewPublisher)
                {
                    publisher = new Publisher { PublisherName = model.PublisherName };
                    unitOfWork.Publishers.Create(publisher);
                    unitOfWork.Save();
                }
                else
                {
                    publisher = unitOfWork.Publishers.GetItem(model.PublisherId);
                }

                Book book = unitOfWork.Books.GetItem(model.BookId);
                book.Name = model.Name;
                book.PublisherId = publisher.PublisherId;
                book.AuthorId = author.AuthorId;
                book.GenreId = genre.GenreId;

                unitOfWork.Books.Update(book);
                unitOfWork.Save();

                return RedirectToAction("BookList");
            }
            else
            {
                Book book = unitOfWork.Books.GetItem(model.BookId);

                var authors = unitOfWork.Authors.GetItemList();
                var genres = unitOfWork.Genres.GetItemList();
                var publishers = unitOfWork.Publishers.GetItemList();

                model.Authors = new SelectList(authors, "AuthorId", "AuthorName");
                model.Genres = new SelectList(genres, "GenreId", "GenreName");
                model.Publishers = new SelectList(publishers, "PublisherId", "PublisherName");

                return View(model);
            }

        }
        #endregion

        #region Удаление книги
        [HttpGet]
        public ActionResult DeleteBook(int id)
        {
            if (unitOfWork.Books.GetBookExtended(id) != null)
            {
                Book book = unitOfWork.Books.GetBookExtended(id);
                DeleteBookViewModel model = new DeleteBookViewModel
                {
                    BookId = book.Id,
                    BookName = book.Name,
                    AuthorName = book.Author.AuthorName,
                    GenreName = book.Genre.GenreName,
                    PublisherName = book.Publisher.PublisherName
                };
                return View(model);
            }
            else
            {
                return NotFound();
            }
        }

        [HttpPost, ActionName("DeleteBook")]
        public ActionResult DeleteBookConfirmed(int id)
        {
            unitOfWork.Books.Delete(id);
            unitOfWork.Save();
            return RedirectToAction("BookList");
        }
        #endregion
    }
}

LibraryCoreProject/Views/Book/AddBook.cshtml
@model LibraryCoreProject.ViewModels.AddBookViewModel
@{
    ViewData["Title"] = "Добавление книги";
}
    <div>
        <a class="btn btn-outline-primary" href="/Book/BookList">Назад</a>
        <h2>Добавить книгу</h2>
        @using (Html.BeginForm())
        {
            @Html.ValidationSummary(true)
            <div class="form-row">
                <div class="col">
                    <div class="form-group">
                        <label asp-for="Name"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-row">
                <div class="col">
                    <div class="form-group">
                        <fieldset>
                            <legend>Автор:</legend>
                            <div class="form-check">
                                <input asp-for="isNewAuthor" type="radio" value="true" class="form-check-input" />
                                <label class="form-check-label">Добавить нового автора</label>
                                <input asp-for="AuthorName" class="form-control" />
                                <span asp-validation-for="AuthorName" class="text-danger"></span>
                            </div>
                            <div class="form-check">
                                <input asp-for="isNewAuthor" type="radio" value="false" class="form-check-input" />
                                <label class="form-check-label">Выбрать автора из списка</label>
                                <select asp-for="AuthorId" asp-items="Model.Authors" class="form-control"></select>
                            </div>
                        </fieldset>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <fieldset>
                            <legend>Жанр:</legend>
                            <div class="form-check">
                                <input asp-for="isNewGenre" type="radio" value="true" class="form-check-input" />
                                <label class="form-check-label">Добавить новый жанр</label>
                            </div>
                            <input asp-for="GenreName" class="form-control" />
                            <span asp-validation-for="GenreName" class="text-danger"></span>

                            <div class="form-check">
                                <input asp-for="isNewGenre" type="radio" value="false" class="form-check-input" />
                                <label class="form-check-label">Выбрать жанр из списка</label>
                                <select asp-for="GenreId" asp-items="Model.Genres" class="form-control"></select>
                            </div>
                        </fieldset>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <fieldset>
                            <legend>Издатель:</legend>
                            <div class="form-check">
                                <input asp-for="isNewPublisher" type="radio" value="true" class="form-check-input" />
                                <label class="form-check-label">Добавить нового издателя</label>
                                <input asp-for="PublisherName" class="form-control" />
                                <span asp-validation-for="PublisherName" class="text-danger"></span>
                            </div>
                            <div class="form-check">
                                <input asp-for="isNewPublisher" type="radio" value="false" class="form-check-input" />
                                <label class="form-check-label">Выбрать издателя из списка</label>
                                <select asp-for="PublisherId" asp-items="Model.Publishers" class="form-control"></select>
                            </div>
                        </fieldset>

                    </div>
                </div>
            </div>

            <input type="submit" value="Добавить" class="form-control" />
        }

    </div>

LibraryCoreProject/Views/Book/BookList.cshtml
@using LibraryCoreProject.ViewModels
@model BooksFilterViewModel
@{
    ViewData["Title"] = "Поиск книг";
}

    <div class="float-right">
        <h2 class="d-inline">Список книг</h2>
        <a asp-action="AddBook" class="btn btn-primary">Добавить книгу</a>
    </div>
    

<div>
    <section class="catalog-filters">
        <form asp-action="BookList" asp-controller="Book">
            <label asp-for="Authors"></label>
            @Html.DropDownList("AuthorId", Model.Authors as SelectList, optionLabel: "Все")
            <label asp-for="Genres"></label>
            @Html.DropDownList("GenreId", Model.Genres as SelectList, optionLabel: "Все")
            <label asp-for="Publishers"></label>
            @Html.DropDownList("PublihserId", Model.Publishers as SelectList, optionLabel: "Все")
            @Html.TextBox("searchString")

        <input class="btn btn-outline-primary" type="submit" value="Фильтр" />
        </form>
    </section>
    <div id="searchresults">
        <table class="table">
            <tr>
                <th>
                    Название книги
                </th>
                <th>
                    Жанр
                </th>
                <th>
                    Автор
                </th>
                <th>
                    Издатель
                </th>
                <th></th>
            </tr>
            @foreach (var item in Model.Books)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Genre.GenreName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Author.AuthorName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Publisher.PublisherName)
                    </td>
                    <td>
                        @Html.ActionLink("Редактировать", "EditBook", new { id = item.Id }) |
                        @Html.ActionLink("Удалить", "DeleteBook", new {id = item.Id })
                    </td>
                </tr>
            }
        </table>
    </div>

</div>

LibraryCoreProject/Views/Book/DeleteBook.cshtml
@model LibraryCoreProject.ViewModels.DeleteBookViewModel
@{
    ViewData["Title"] = "Удаление книги";
}

    <div>
        <label asp-for="BookName"></label>
        <strong>@Model.BookName</strong>
        <label asp-for="AuthorName"></label>
        <strong>@Model.AuthorName</strong>
        <label asp-for="GenreName"></label>
        <strong>@Model.GenreName</strong>
        <label asp-for="PublisherName"></label>
        <strong>@Model.PublisherName</strong>
        <form method="post">
            <input type="hidden" asp-for="BookId" />
            <input type="submit" value="Удалить" class="form-control"/>
        </form>
    </div>

LibraryCoreProject/Views/Book/EditBook.cshtml
@model LibraryCoreProject.ViewModels.AddBookViewModel
@{
    ViewData["Title"] = "EditBook";
}

<h1>EditBook</h1>

<h2>Редактировать книгу</h2>
@using (Html.BeginForm())
{

    @Html.HiddenFor(m => Model.BookId);
    @Html.ValidationSummary(true)
    <p>Название книги:</p>
    @Html.EditorFor(model => model.Name)
    @Html.ValidationMessageFor(model => model.Name)
    <p>Автор:</p>
    <p>@Html.RadioButton("isNewAuthor", true) Добавить нового автора</p>
    <p>@Html.RadioButton("isNewAuthor", false) Выбрать автора из списка</p>
    <div class="editor-field">
        @Html.EditorFor(model => model.AuthorName)
        @Html.ValidationMessageFor(model => model.AuthorName)
    </div>
    <div class="editor-field">
        @Html.DropDownList("AuthorId", Model.Authors as SelectList)
    </div>

    <p>Жанр:</p>
    <p>@Html.RadioButton("isNewGenre", true) Добавить новый жанр</p>
    <p>@Html.RadioButton("isNewGenre", false) Выбрать жанр из списка</p>
    <div class="editor-field">
        @Html.EditorFor(model => model.GenreName)
        @Html.ValidationMessageFor(model => model.GenreName)
    </div>
    @Html.DropDownList("GenreId", Model.Genres as SelectList)

    <p>Издатель:</p>
    <p>@Html.RadioButton("isNewPublisher", true) Добавить нового издателя</p>
    <p>@Html.RadioButton("isNewPublisher", false) Выбрать издателя из списка</p>
    <div class="editor-field">
        @Html.EditorFor(model => model.PublisherName)
        @Html.ValidationMessageFor(model => model.PublisherName)
    </div>
    @Html.DropDownList("PublisherId", Model.Publishers as SelectList)

    <input type="submit" value="Сохранить" />
}

<div>
    @Html.ActionLink("Вернуться к списку", "BookList")
</div>